# Generated by Django 4.2.30 on 2026-06-27 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGradedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Auto Graded Activities',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='level_type',
            field=models.CharField(choices=[('EARLY_YEARS', 'Early Years'), ('PRIMARY_LOWER', 'Primary & Lower Secondary'), ('IGCSE', 'Upper Secondary / IGCSE')], default='PRIMARY_LOWER', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='erp_core.autogradedactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to='erp_core.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RawMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('assessment_type', models.CharField(max_length=50)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_marks', to='erp_core.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('plan_type', models.CharField(choices=[('UPLOAD', 'Upload Document'), ('STRUCTURED', 'Structured Template')], default='UPLOAD', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_plans/')),
                ('objectives', models.TextField(blank=True, null=True)),
                ('materials', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('evaluation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.class')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_plans', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningAreaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_area', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('EMERGING', 'Emerging (🟢)'), ('DEVELOPING', 'Developing (🟡)'), ('SECURE', 'Secure (🔵)'), ('EXCEEDING', 'Exceeding (⭐)')], max_length=20)),
                ('observation_text', models.TextField(blank=True, null=True)),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='erp_core.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='autogradedactivity',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='erp_core.class'),
        ),
        migrations.AddField(
            model_name='autogradedactivity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=2)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='erp_core.autogradedactivity')),
            ],
        ),
        migrations.CreateModel(
            name='GradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('A-G', 'Cambridge A-G'), ('1-9', 'Cambridge 1-9')], max_length=10)),
                ('grade_letter', models.CharField(max_length=5)),
                ('min_percentage', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boundaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Grade Boundaries',
                'unique_together': {('framework', 'grade_letter')},
            },
        ),
    ]
