# Generated by Django 4.2.30 on 2026-06-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_autogradedactivity_class_level_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmark',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
