# Generated by Django 4.2.30 on 2026-06-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0004_payroll_payslip_staffsalaryconfig_staffdeduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='term',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='billing_mode',
            field=models.CharField(choices=[('YEARLY', 'Once a year'), ('TERMLY', 'Termly'), ('LIFETIME', 'One-time Lifetime Fee')], default='TERMLY', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='due_term',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='vote_head',
            field=models.CharField(default='Tuition Fee', max_length=150),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='year',
            field=models.CharField(default='2026', max_length=20),
        ),
    ]
