# Generated by Django 4.2.30 on 2026-06-27 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def populate_subjects(apps, schema_editor):
    Subject = apps.get_model('erp_core', 'Subject')
    RawMark = apps.get_model('erp_core', 'RawMark')
    LearningAreaProgress = apps.get_model('erp_core', 'LearningAreaProgress')
    
    # Default subject to link if any
    default_sub, _ = Subject.objects.get_or_create(
        name='General',
        defaults={'level': 'PRIMARY_LOWER'}
    )
    
    # Migrate RawMarks
    for rm in RawMark.objects.all():
        sub_name = getattr(rm, 'subject_old', 'General') or 'General'
        sub_obj, _ = Subject.objects.get_or_create(
            name=sub_name,
            defaults={'level': 'PRIMARY_LOWER'}
        )
        rm.subject = sub_obj
        rm.save()
        
    # Migrate LearningAreaProgress
    for lap in LearningAreaProgress.objects.all():
        area_name = getattr(lap, 'learning_area_old', 'General') or 'General'
        sub_obj, _ = Subject.objects.get_or_create(
            name=area_name,
            defaults={'level': 'EARLY_YEARS'}
        )
        lap.subject = sub_obj
        lap.save()

class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0005_remove_feestructure_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('EARLY_YEARS', 'Early Years (Learning Area)'), ('PRIMARY_LOWER', 'Primary & Lower Secondary'), ('IGCSE', 'Upper Secondary / IGCSE')], default='PRIMARY_LOWER', max_length=20)),
            ],
        ),
        # Rename RawMark.subject to subject_old
        migrations.RenameField(
            model_name='rawmark',
            old_name='subject',
            new_name='subject_old',
        ),
        # Add new subject FK to RawMark
        migrations.AddField(
            model_name='rawmark',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_marks', to='erp_core.subject'),
        ),
        # Rename LearningAreaProgress.learning_area to learning_area_old
        migrations.RenameField(
            model_name='learningareaprogress',
            old_name='learning_area',
            new_name='learning_area_old',
        ),
        # Add new subject FK to LearningAreaProgress
        migrations.AddField(
            model_name='learningareaprogress',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress_records', to='erp_core.subject'),
        ),
        # Run Python script
        migrations.RunPython(populate_subjects),
        # Make the FK non-nullable
        migrations.AlterField(
            model_name='rawmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_marks', to='erp_core.subject'),
        ),
        migrations.AlterField(
            model_name='learningareaprogress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress_records', to='erp_core.subject'),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='rawmark',
            name='subject_old',
        ),
        migrations.RemoveField(
            model_name='learningareaprogress',
            name='learning_area_old',
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='erp_core.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='erp_core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'class_obj', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='erp_core.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
