# Generated by Django 4.2.30 on 2026-07-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0006_subject_remove_learningareaprogress_learning_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningareaprogress',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress_records', to='erp_core.subject'),
        ),
        migrations.AlterField(
            model_name='rawmark',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raw_marks', to='erp_core.subject'),
        ),
    ]
