# Generated by Django 4.2.30 on 2026-07-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0007_alter_learningareaprogress_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('STATIONERY', 'Stationery & Books'), ('UNIFORM', 'School Uniforms'), ('FURNITURE', 'Furniture & Equipment'), ('CLEANING', 'Cleaning & Sanitation'), ('ELECTRONICS', 'IT & Electronics'), ('OTHER', 'Other Supplies')], default='STATIONERY', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reorder_level', models.IntegerField(default=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=20)),
                ('route_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('capacity', models.IntegerField(default=30)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='transport_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='erp_core.transportroute'),
        ),
    ]
