# Generated by Django 4.2.30 on 2026-07-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0008_stockitem_transportroute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.IntegerField(default=1)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='erp_core.lessonplan')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_requirements', to='erp_core.stockitem')),
            ],
        ),
    ]
