# Generated by Django 4.2.30 on 2026-07-02 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0010_biometricdevice_customuser_biometric_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In (Purchase/Restock)'), ('OUT', 'Stock Out (Consumption/Issue)')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.CharField(choices=[('STATIONERY', 'Stationery & Books'), ('UNIFORM', 'School Uniforms'), ('FURNITURE', 'Furniture & Equipment'), ('CLEANING', 'Cleaning & Sanitation'), ('ELECTRONICS', 'IT & Electronics'), ('KITCHEN', 'Kitchen Consumables'), ('OTHER', 'Other Supplies')], default='STATIONERY', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='LessonPlanMaterialRequirement',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='erp_core.stockitem'),
        ),
    ]
