# Generated by Django 4.2.30 on 2026-07-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0012_bankdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='bank_name',
            field=models.CharField(choices=[('EXIM', 'Exim Bank'), ('CRDB', 'CRDB Bank'), ('PBZ', "People's Bank of Zanzibar (PBZ)")], default='CRDB', max_length=20),
        ),
    ]
