# Generated by Django 4.2.30 on 2026-07-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0013_bankdeposit_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
