# Generated by Django 4.2.30 on 2026-07-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0014_bankdeposit_account_number_bankdeposit_sender_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdb_account', models.CharField(default='01XXXXXXXXXX', max_length=50)),
                ('exim_account', models.CharField(default='XXXXXXXXXXXX', max_length=50)),
                ('pbz_account', models.CharField(default='XXXXXXXXXXXX', max_length=50)),
                ('whatsapp_provider', models.CharField(choices=[('TWILIO', 'Twilio WhatsApp Sandbox'), ('AFRICASTALKING', "Africa's Talking"), ('META', 'Meta WhatsApp Business Direct')], default='TWILIO', max_length=20)),
                ('whatsapp_api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_sender_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
