# Generated by Django 4.2.30 on 2026-07-07 04:03

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0017_cambridgestage_cambridgesubject_quiz_quizattempt_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='SyllabusEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('TOPIC', 'Syllabus Topic'), ('OBJECTIVE', 'Learning Objective'), ('KNOWLEDGE', 'Knowledge Base Item'), ('EXAMPLE', 'Worked Example'), ('PAST_QUESTION', 'Past Exam Question'), ('DEFINITION', 'Definition')], max_length=20)),
                ('content_text', models.TextField(help_text='The raw text that was converted to an embedding')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('stage', models.CharField(db_index=True, max_length=100)),
                ('stage_type', models.CharField(db_index=True, max_length=20)),
                ('unit_title', models.CharField(blank=True, max_length=200)),
                ('topic_title', models.CharField(blank=True, max_length=200)),
                ('section_title', models.CharField(blank=True, max_length=200)),
                ('difficulty', models.CharField(blank=True, max_length=10)),
                ('cognitive_level', models.CharField(blank=True, max_length=20)),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2', help_text='Model used to generate this embedding', max_length=100)),
                ('embedding_dimensions', models.IntegerField(default=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='erp_core.syllabusknowledgebase')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='erp_core.syllabuslearningobjective')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='erp_core.syllabustopic')),
            ],
            options={
                'verbose_name': 'Syllabus Embedding',
                'verbose_name_plural': 'Syllabus Embeddings',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='syllabus_embedding_hnsw_idx', opclasses=['vector_cosine_ops']), models.Index(fields=['content_type', 'subject', 'stage_type'], name='embedding_filter_idx'), models.Index(fields=['topic'], name='embedding_topic_idx')],
            },
        ),
    ]
