# Generated by Django 4.2.30 on 2026-07-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0018_syllabusembedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='nssf_deduction',
            new_name='zssf_deduction',
        ),
        migrations.RenameField(
            model_name='staffsalaryconfig',
            old_name='nssf_deduction',
            new_name='zssf_deduction',
        ),
    ]
