# Generated by Django 4.2.30 on 2026-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0019_remove_syllabusembedding_syllabus_embedding_hnsw_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employment_status',
            field=models.CharField(choices=[('CONTRACT', 'Contract'), ('PROBATION', 'Probation'), ('PERMANENT', 'Permanent')], default='PERMANENT', max_length=20),
        ),
    ]
